name: Daily Job

on:
  # 定时触发：每天UTC时间的00:00执行
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:  # 添加 workflow_dispatch 触发器

jobs:
  run_java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 设置 Java 环境
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 指定你需要的 Java 版本
          distribution: 'adopt'  # 指定 distribution 参数为 adopt 或其他有效值
          
      - name: 缓存 Maven 依赖
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # 缓存 Maven 默认的本地仓库路径
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # 根据 pom.xml 文件内容生成缓存的 key


      - name: 构建 Java 项目
        run: mvn clean install  # 替换为你的项目构建命令


      - name: 运行 Java 程序
        run: java -jar target/quan-min-k-ge-action-1.0-SNAPSHOT.jar $COOKIE $UID
        env:
          COOKIE: ${{ secrets.MY_SECRET_COOKIE }}
          UID: ${{ secrets.MY_SECRET_UID }}
